version: 878.30.4b{build}
skip_commits:
  files:
    - mDNSPosix/*
    - mDNSshared/dnsextd*
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  project: mDNSWindows\SystemService\Service.vcxproj
  verbosity: minimal
